### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by yenoh2** [quiet/quiet-js#11]
When I try to setup and run your examples, I get the following error:  
Uncaught TypeError: Quiet.setProfilesPrefix is not a function

Please help.  I've spent half a day troubleshooting to no avail.

**Comment by brian-armstrong** [comment]
Eep, I'm sorry. I forgot that I still need to do this.

Have a look at this issue https://github.com/quiet/quiet-js/issues/10

Basically, initialization is done with a single function with a map of values now

Sorry for your frustrations :(

**Comment by yenoh2** [comment]
No apology necessary. I didn't want you to think I was bugging you without
giving it some effort.  Thank you this project is impressive!

**Comment by brian-armstrong** [comment]
Please don't hesitate to ask if you get stuck again. The pieces have moved around quickly so I know there are some rough edges. If you're using quiet.js as part of a project then that's very cool :)

**Comment by brian-armstrong** [comment]
I pushed an update to the master branch. I tested the examples and they do now work. If you get a chance, please try them again and let me know how it goes. Thanks :)

**Comment by yenoh2** [comment]
Awesome!  Thank you.  I'll give it a try.

I noticed that it strips carriage returns and extra white spaces.  Is there
a way to transmit them also?

**Comment by brian-armstrong** [comment]
What an excellent question! It's because I was putting the text into `<p></p>` tags. I switched the example to instead use `<pre></pre>` tags, and it looks much better. Try it now :)

**Comment by brian-armstrong** [comment]
Closing since this is fixed
