### ISSUE TITLE
could the examples run locally?

### ISSUE THREAD

**Issue by dimpapadop** [quiet/quiet-js#13]
Is there any way to run locally (for example by double click the html from my hdd)

I am getting some errors when trying to do that.

Thank you and great and impressive work you have here.

Dimitrios

**Comment by brian-armstrong** [comment]
@dimpapadop 

Hi, thanks for trying quiet

What error are you getting specifically, and which OS are you using? I believe the easiest way to handle this on OSX/linux is to set up nginx pointed at some part of your local filesystem

**Comment by dimpapadop** [comment]
hi brian. I am using windows.
It;s really impressive.

the errors i get is
XMLHttpRequest cannot load file:///D:/javascripts/quiet-profiles.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.
..... and also for 
XMLHttpRequest cannot load file:///D:/!00%20PROJECTS/DATA%20THROUGH%20SOUND/quiet-quiet-js-be8bbc0/examples/send_rec/javascripts/quiet-emscripten.js.mem. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

i'd like to test it also via a cordova app

thank you

**Comment by brian-armstrong** [comment]
http://stackoverflow.com/a/18137280/6052863 This might help you

**Comment by dimpapadop** [comment]
thank you.
I was actually reading that article and suggestions too.

congratulations again!

**Comment by brian-armstrong** [comment]
@dimpapadop Did it help?

**Comment by dimpapadop** [comment]
brian by cmd line opening chrome letting access files 2 / 3 errors  were eliminated.
I think i'll find a way.

I'll also try to see if it can be run in a cordova app with an embedded httpd

**Comment by iuvi7** [comment]
> brian by cmd line opening chrome letting access files 2 / 3 errors were eliminated. I think i'll find a way.
> 
> I'll also try to see if it can be run in a cordova app with an embedded httpd

Any sucess? Thanks
