### ISSUE TITLE
Data rate and Encryption

### ISSUE THREAD

**Issue by ekoome** [quiet/quiet-js#16]
Great library. A couple of questions:

What is the data transmission rate in quiet mode (bits/s)?

Also what would be a suitable encryption scheme to use without impacting the data rate?

**Comment by brian-armstrong** [comment]
Hi Eric,

Go ahead and try out https://quiet.github.io/quiet-profile-lab to see the
speed

Crypto should work the same as any other data transmission. You may have to
be somewhat clever in terms of breaking data up into small enough frames.

Cheers
Brian
