### ISSUE TITLE
Online demo doesn't work on mobiles

### ISSUE THREAD

**Issue by yaroslav-perec** [quiet/quiet-js#38]
Hello there,

I've tried the [online example](https://quiet.github.io/quiet-js/index.html) and it works well on my laptop, but it doesn't work on my mobile, for testing, I used iPhone 11 and different browsers (Chrome and Safari) when I try to send text, my mobile doesn't produce any sound (I've tried both audible and ultrasonic option).

Is this example supposed to work on mobiles?

**Comment by brian-armstrong** [comment]
Hello,

It works for me on mobile Safari, but I need to flip the mute switch on. I'm guessing there is something needed for mobile Safari to avoid this. Does that fix it for you at least?

**Comment by yaroslav-perec** [comment]
@brian-armstrong 

Yes, the problem was with silent mode, thanks a lot!
